#!/bin/bash

export GEVENT_SUPPORT=True
export PYDEVD_DISABLE_FILE_VALIDATION=1

/opt/odoo/venv/bin/python -m debugpy --wait-for-client --listen 0.0.0.0:5678 /var/opt/src/OCB/odoo-bin --config=/etc/odoo/odoo.conf --dev=all
