services:
  odoo16-community:
    build:
      context: .
    container_name: odoo16-community
    depends_on:
      - db
    ports:
      - "16000:8069"
      - "5678:5678"
    volumes:
      - odoo-web:/var/lib/odoo
      - ./config:/etc/odoo
      - ../custom_addons:/mnt/custom-addons
      - ../oca_addons:/mnt/oca-addons
      - ../third_party:/mnt/third-party-addons
      - ../LMS:/mnt/lms-addons
      - ../enterprise:/mnt/enterprise-addons
    environment:
      - PYTHONUNBUFFERED=0
    restart: always
    networks:
      - postgres_bd
  db:
    image: postgres:16
    container_name: db
    ports:
      - "19000:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - postgres_bd
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jdap.dmc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - postgres_bd
    volumes:
        - pgadmin:/root/.pgadmin

    ports:
      - "8080:80"    
    restart: unless-stopped

networks:
  postgres_bd:

volumes:
  odoo-web:
  odoo-db:
  pgadmin:
